# Generated by Django 3.2.7 on 2021-09-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=2000, null=True)),
                ('sku', models.CharField(max_length=2000, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('all_images', models.TextField()),
                ('main_image', models.URLField(max_length=2000)),
                ('breadcrumbs', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=2000)),
                ('short_desc', models.CharField(max_length=2000)),
                ('keywords', models.CharField(max_length=2000)),
                ('manufacturer', models.CharField(default='CKK Industries', max_length=255)),
            ],
        ),
    ]
