# Generated by Django 3.2.7 on 2021-09-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnifekitsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=5000)),
                ('description', models.TextField()),
                ('main_image', models.URLField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=1000)),
                ('has_video', models.BooleanField(default=False)),
                ('has_discounts', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=255)),
                ('image_links', models.TextField()),
                ('breadcrumbs', models.TextField()),
                ('first_crawl', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
